### PR TITLE
Add applyRouterMiddleware function declaration

### PR DESCRIPTION
**Pull request by martianov**
Hi,

I've added missing declaration for applyRouterMiddleware function.  It's very helpful for Router customization (for example, with 'react-router-scroll').

### CODE REVIEW

**Comment by unional** [comment]
Interesting. I didn't know you can put the generic `<IProp>` at the return signature.

**Comment by unional** [comment]
Is this a new functionality added at a newer version? (about `applyRouterMiddleware`)

**Comment by martianov** [comment]
Relatively new..  applyRouterMiddleware was introduced in react-router 2.3.0

**Comment by unional** [comment]
Thanks. Since this is marked as 2.4.0 on the registry, it is fine. I also updated `typings.json/version` to reflect that.

**Pull request merged**
